events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;

    # Increase the maximum allowed size of the client request body
    client_max_body_size 30M;

    server {
        listen 80;
        listen [::]:80;
        server_name localhost;

        # Increase the maximum allowed size of the client request body
        client_max_body_size 30M;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|otf|json)$ {
            try_files $uri =404;
        }
    }
}
