FROM alpine:latest

ARG PB_VERSION=0.36.5

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# uncomment to copy the local pb_migrations dir into the image
# ถ้าไม่มี pb_migrations ให้สร้างขึ้นมาใหม่
# RUN mkdir -p /dev/pb_migrations
# COPY ./dev/pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_hooks dir into the image
# ถ้าไม่มี pb_hooks ให้สร้างขึ้นมาใหม่
# RUN mkdir -p /dev/pb_hooks
# COPY ./dev/pb_hooks /pb/pb_hooks

EXPOSE 8080

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]