FROM alpine:latest

ARG PB_VERSION=0.36.5

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
# ใช้ TARGETARCH เพื่อรองรับทั้ง amd64 และ arm64 โดยอัตโนมัติ
ARG TARGETARCH

RUN if [ "$TARGETARCH" = "amd64" ]; then \
        export PB_ARCH="amd64"; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        export PB_ARCH="arm64"; \
    elif [ "$TARGETARCH" = "arm" ]; then \
        export PB_ARCH="armv7"; \
    fi; \
    wget https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_${PB_ARCH}.zip -O /tmp/pb.zip && \
    unzip /tmp/pb.zip -d /pb/ && \
    rm /tmp/pb.zip

# uncomment to copy the local pb_migrations dir into the image
# ถ้าไม่มี pb_migrations ให้สร้างขึ้นมาใหม่
# RUN mkdir -p /dev/pb_migrations
# COPY ./dev/pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_hooks dir into the image
# ถ้าไม่มี pb_hooks ให้สร้างขึ้นมาใหม่
# RUN mkdir -p /dev/pb_hooks
# COPY ./dev/pb_hooks /pb/pb_hooks

EXPOSE 8080

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]