services:
  pocketbase:
    container_name: pocketbase-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:8080
    volumes:
      - ./dev/pb_migrations:/pb/pb_migrations
      - ./dev/pb_hooks:/pb/pb_hooks
      - ./dev/pb_data:/pb/pb_data